### ISSUE TITLE
The method setDebug(boolean) is undefined for the type BasicConnectionPool

### ISSUE THREAD

**Issue by Jens2205** [jlolling/talendcomp_tDatabaseConnectionPool#4]
Hi Jan,

we found the following issue by using the component tPostgresqlConnectionPool in Talend-Enterprise-Studio 7.3

`if (dsAlreadyExists_tPostgresqlConnectionPool_1 == false) {
					de.cimt.talendcomp.connectionpool.BasicConnectionPool
							.info("Create new database pool with alias: " + "PostgresqlConnectionPool");
					String connectionString_tPostgresqlConnectionPool_1 = "jdbc:postgresql://"
							+ context.Postgres_ManagedDB_Server + ":" + context.Postgres_ManagedDB_Port + "/"
							+ context.Postgres_ManagedDB_Database;
					de.cimt.talendcomp.connectionpool.BasicConnectionPool tPostgresqlConnectionPool_1 = new de.cimt.talendcomp.connectionpool.BasicConnectionPool(
							connectionString_tPostgresqlConnectionPool_1, context.Postgres_ManagedDB_Login,
							context.Postgres_ManagedDB_Password);
					de.cimt.talendcomp.connectionpool.BasicConnectionPool.**setDebug(false);**
`
The error on setDebug(false) is: "The method setDebug(boolean) is undefined for the type BasicConnectionPool"

Can you have a look on this? 

Thanks in advance! :-)

**Comment by jlolling** [comment]
Yees, sorry, I had actually already solved this issue but forgot to update the releases here.
Please download the release 2.9 here in Github.
I will not update Talend Exchange anymore because Talend Exchange will be shutdown in Juli 2023.
